apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: summit-api
  labels:
    app: summit-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: summit-api-deployment
    spec:
      containers:
      - name: summit-api
        image: ykoyfman/summit-api:1
        ports:
          - containerPort: 9080
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: summit-svc
  labels:
    app: summit-api
spec:
  clusterIP: None
  ports:
    - port: 9080
      targetPort: 9080
  selector:
    name: summit-api-deployment
