kind: Service
apiVersion: v1
metadata:
  name: summit-api
  labels:
    app: summit-api
spec:
  selector:
    app: summit-api
  ports:
    - port: 9080
      name: http
  type: NodePort
---

kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: summit-api
spec:
  replicas: 1
  template:
    metadata:
      annotations: 
        sidecar.istio.io/inject: "true"    
      labels:
        app: summit-api
        version: v1
    spec:
      containers:
      - name: summit-api
        image: ykoyfman/ol-ubi-summit:latest
        ports:
        - containerPort: 9080
        imagePullPolicy: Always
        env:
        - name: ENV_MYSQL_URL
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: db_host
        - name: ENV_MYSQL_PORT
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: db_port
        - name: ENV_MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: db_username
        - name: ENV_MYSQL_PWD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: db_password
        - name: ENV_MYSQL_DB_NAME
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: db_name
      restartPolicy: Always
---
